extern char *mmio_addr_alloc_kernel_start,
            *mmio_addr_alloc_text_start,
            *mmio_addr_alloc_text_end,
            *mmio_addr_alloc_bss_start,
            *mmio_addr_alloc_bss_end,
            *mmio_addr_alloc_rodata_start,
            *mmio_addr_alloc_rodata_end,
            *mmio_addr_alloc_data_start,
            *mmio_addr_alloc_data_end,
            *mmio_addr_alloc_kernel_end;